### ISSUE TITLE
Unable to 'setShootMode'

### ISSUE THREAD

**Issue by mungewell** [Bloodevil/sony_camera_api#10]
Not sure how I should be issuing commands, but the following fails on my cameras
```
      camera = SonyAPI()
      mode = camera.getAvailableShootMode()
      if (mode['result'])[0] != 'movie':
         if 'movie' in (mode['result'])[1]:
            camera.setShootMode("movie")
         else:
            print "'movie' mode not supported"
```

Which seems to be getting fragmented to the following in 'def _cmd(self, method=None, param=[]):',
```
{'version': '1.0', 'params': ['m', 'o', 'v', 'i', 'e'], 'method': 'setShootMode', 'id': 1}
```

**Comment by mungewell** [comment]
Figured that the command should be:
```
      if (mode['result'])[0] != 'movie':
         if 'movie' in (mode['result'])[1]:
            camera.setShootMode(["movie"])
         else:
            print "'movie' mode not supported"
```

But 'pysony.py' should clear the params as it effects next calls.
```
        if param:
            self.params["params"] = self._truefalse(param)
        else:
            self.params["params"] = []
```

**Comment by mungewell** [comment]
I'm in the process of converting one of my other applications (pyDataMatrixScanner) to work as an GUI example, and I'm happy to say it's mostly working on Linux and Windows.... I'll leave this here as a tease ;-)

![pyliveview_tease](https://cloud.githubusercontent.com/assets/236907/6786594/fe0756c6-d152-11e4-9dbc-a9564f4ada02.png)

**Comment by Bloodevil** [comment]
wow nice job!! thanks and I will patch that you said things. thanks for using!!
