### ISSUE TITLE
liveview url

### ISSUE THREAD

**Issue by mikkab** [Bloodevil/sony_camera_api#15]
QX1 send me a url for liveview as http:\\\\/\\\\/192.168.122.1:8080\\\\/liveview\\\\/liveviewstream which is incorrect for urllib2 and function SonyAPI.liveview() return dict instead of urllib2 object.
add following code to prevent this situation:

if isinstance(f, dict):
        url = f['result'][0]
        f = urllib2.urlopen(url.replace('\\\\', ''))

Thanks

**Comment by Bloodevil** [comment]
I resolve this issue. I close after testing.

Thanks.

**Comment by Bloodevil** [comment]
I updated pypi as version 0.1.10

**Comment by krisrok** [comment]
i tried out timer_photo.py and had to add the following replace statement to make it work:
```liveview_url = (live['result'][0]).replace("\\/", "/")```

before the liveview url looked like http:\/\/localhost\/etc..
