### ISSUE TITLE
Unable to 'setLiveviewFrameInfo()'

### ISSUE THREAD

**Issue by mungewell** [Bloodevil/sony_camera_api#19]
`
$ python 
Python 2.7.9 (default, Apr  2 2015, 15:34:55) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysony
>>> camera = pysony.SonyAPI(QX_ADDR='http://192.168.122.1:8080/')
>>> camera.setLiveviewFrameInfo([{"frameInfo": True}])
Trying.. {"version": "1.0", "params": [], "method": "getAvailableApiList", "id": 1}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-i686/egg/pysony.py", line 229, in setLiveviewFrameInfo
  File "build/bdist.linux-i686/egg/pysony.py", line 168, in _cmd
  File "build/bdist.linux-i686/egg/pysony.py", line 146, in _truefalse
AttributeError: 'dict' object has no attribute 'lower'
`

**Comment by mungewell** [comment]
![screenshot_2016-03-15_21-17-57](https://cloud.githubusercontent.com/assets/236907/13801158/e87d4d9e-eaf4-11e5-9728-3b8a2f26807f.png)

[https://github.com/mungewell/sony_camera_api/tree/frame_info](url)

Start with
`
$ python src/example/pyLiveView.py -g -i
`

**Comment by Bloodevil** [comment]
Thanks  for reporting. I fixed this bug like below:
`
        for x in param:
            if type(x) != str:
                params.append(x)
            else:
                if x.lower() == 'true':
                    params.append(True)
                elif x.lower() == 'false':
                    params.append(False)
                else:
                    params.append(x)
`
