### ISSUE TITLE
Running on Mac

### ISSUE THREAD

**Issue by korrio** [Bloodevil/sony_camera_api#30]
After connecting to camera WIFI (QX10)

Korr:sony_camera_api Mac$ python src/example/pygameLiveView.py
Traceback (most recent call last):
  File "src/example/pygameLiveView.py", line 90, in <module>
    cameras =  search.discover()
  File "build/bdist.macosx-10.9-intel/egg/pysony.py", line 46, in discover
socket.error: [Errno 51] Network is unreachable

**Comment by hblanken** [comment]
I have a similar issue, running on python 2.7.10, MacOS 10.11.6, direct WiFi connection to QX10:

python scan_for_cameras.py
Traceback (most recent call last):
  File "scan_for_cameras.py", line 6, in <module>
    cameras =  search.discover(5)
  File "/usr/local/lib/python2.7/site-packages/pysony.py", line 38, in discover
    self.__udp_socket.sendto(msg, (SSDP_ADDR, SSDP_PORT))
socket.error: [Errno 51] Network is unreachable

The examples for sony_live and timer_photo work well. Any suggestions on how to fix this discovery issue on Mac?

**Comment by Bloodevil** [comment]
@hblanken is right. I tested several times but SSDP discovery is not working well. so after connect the camera WIFI and run the sony_live or timer_photo. and if you success to connect to camera. you can skip the discover part on pygameLiveView example.
