### ISSUE TITLE
example/sony_camera_liveview.py code could not work at the a6000

### ISSUE THREAD

**Issue by flow-dev** [Bloodevil/sony_camera_api#34]
I tried the live view sample code by a6000, i could not got the liveview jpeg dump. When I read the official reference it turned out that old models can not transition to liveview mode unless they hit "StartRecMode" after camera start . It solved this. For your information.

**Comment by mungewell** [comment]
Hi,
Late to reply, but thanks for the report. The example code should already call 'StartRecMode()' if the camera has that function available.
https://github.com/Bloodevil/sony_camera_api/blob/master/src/example/pyLiveView.py#L95

Can you run 'dump_camera_capabilities.py' and post the results.

Note that for the a6000 you will need to install the improved 'Smart Remote Control' application on the _camera_, the pre-installed app is fairly basic.
https://www.playmemoriescameraapps.com/portal/usbdetail.php?eid=IS9104-NPIA09014_00-F00002
