### ISSUE TITLE
python3: comp_urllib not found.

### ISSUE THREAD

**Issue by mungewell** [Bloodevil/sony_camera_api#41]
Looks like the recent changes in commit 8dd4ae27 don't work for Python3 (on Xubuntu).

```
$ python3 src/example/dump_camera_capabilities.py 
Traceback (most recent call last):
  File "src/example/dump_camera_capabilities.py", line 1, in <module>
    import pysony
  File "/usr/local/lib/python3.5/dist-packages/pysony-0.1.11-py3.5.egg/pysony.py", line 9, in <module>
ImportError: No module named 'comp_urllib'
```

**Comment by mungewell** [comment]
seems that the 'comp_urllib' is now included in the src directory, but is not linked into the resultant module. I suspect the code works if run locally, but once installed to 'dist-packages' it fails.

Temporary/hacky workaround attached as a method getting pySony working under python3, would not work with python2.
[temp_fix.txt](https://github.com/Bloodevil/sony_camera_api/files/1385108/temp_fix.txt)

**Comment by mungewell** [comment]
better workaround attached.
[temp_fix2.txt](https://github.com/Bloodevil/sony_camera_api/files/1393569/temp_fix2.txt)

**Comment by Bloodevil** [comment]
merged
