### ISSUE TITLE
_cmd Method from pysony.py is missing minversion variable

### ISSUE THREAD

**Issue by raza-elahi** [Bloodevil/sony_camera_api#62]
Method signature 

>def _cmd(self, method=None, param=[], target=None)://Line 283, pysony.py

Adding the variable with a default value of 1.0 to the method works. 

It also does not have the verison variable. 

final signature looks like 

> def _cmd(self, method=None, param=[], target=None, version=1.0,  minversion="1.0")

**Comment by danielrosero** [comment]
> Method signature
> 
> > def _cmd(self, method=None, param=[], target=None)://Line 283, pysony.py
> 
> Adding the variable with a default value of 1.0 to the method works.
> 
> It also does not have the verison variable.
> 
> final signature looks like
> 
> > def _cmd(self, method=None, param=[], target=None, version=1.0,  minversion="1.0")

Thanks, this helped me a lot.

I was facing this issue:
`TypeError: _cmd() got an unexpected keyword argument 'version'
`

**Comment by Bloodevil** [comment]
thanks all! i added version and min version to develop branch. I'll merge and update soon. :)
