### ISSUE TITLE
zoom sony camera 

### ISSUE THREAD

**Issue by SureshbabuAkash1999** [Bloodevil/sony_camera_api#65]
I'm new to programming. Could you please create a code to zoom the camera as i feel its hard to create one.

**Comment by bjmc** [comment]
Hi @akashmon598, it's great you're getting into programming! This is a free open-source project maintained by volunteers, and it's unlikely anyone except you is going to be able to create exactly what you need for your own program.

If you want to adjust the zoom on the camera, that feature is available [using the actZoom method](https://github.com/Bloodevil/sony_camera_api/blob/d65482cb4c10060c6b93ac11a177a17cd1387a55/src/pysony.py#L429)

**Comment by akashmon598** [comment]
Dear Sir,
Thank you so much for your prompt reply. Will check on that and work on the
same.
Yours Sincerly
Akash Sureshbabu
