### ISSUE TITLE
Gtk gui not supported in ubuntu

### ISSUE THREAD

**Issue by SureshbabuAkash1999** [Bloodevil/sony_camera_api#67]
Thank you for such a great library. Sir the problem is gtk gui is not supported in ubuntu. As to the same pylive.py function is not opening it's gui.

**Comment by mungewell** [comment]
Can you please provide some information on what you are running and how it fails (ie. copies of messages on the screen).

This project has be idle for a long time, it is likely that changes to Python (and others) may have exposed bugs. Do any of the other examples work for you??
Simon.

**Comment by mungewell** [comment]
Started to re-visit this library, and yes it seems to be broken at the moment. GTK is supported for _Python2_, but something else is broke.
```
simon@thevoid:~/sony_camera_api-github$ python2 examples/pyLiveView.py -g
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "examples/pyLiveView.py", line 155, in run
    status = mode['result'][1]
KeyError: 'result'

^CKilled
```

It does work from my branched repo, back from 2017...
```
simon@thevoid:~/sony_camera_api-git$ git log | head
commit 7503fecefd119e47f91fe8696443e975fc562902
Author: Simon Wood <simon@mungewell.org>
Date:   Tue Dec 26 13:00:21 2017 -0700

    Add functions and example for 'bulb' shooting.

commit 517e1f3e23a595ad2600a6bebab45ac9f3d7fca1
Merge: 005691d 55baf81
Author: Simon Wood <simon@mungewell.org>
Date:   Wed Dec 20 23:33:23 2017 -0700
```

I'll see if I can find out why.

**Comment by mungewell** [comment]
The fault that I am seeing is that code is now assuming getEvent is now called with version '1.3', patch below checks what the camera supports before calling getEvent.


[check_event_version.patch.txt](https://github.com/Bloodevil/sony_camera_api/files/6217856/check_event_version.patch.txt)
