### ISSUE TITLE
Error using anaconda with python 3.6 

### ISSUE THREAD

**Issue by imihassan** [Bloodevil/sony_camera_api#68]
I installed the module using pip install pysony.

To test I wrote code

`import pysony`
`api = pysony.SonyAPI()`
`api.getAvailableApiList()`

but it is giving this error ...

`SyntaxError: Missing parentheses in call to 'print'. Did you mean print("[WORN] liveview is not a dict type")?`

**Comment by bjmc** [comment]
This has already been fixed in #57.

I don't know how Anaconda decides what version to install, but if you get the latest version of this repo it should work with Python 3.

**Comment by bjmc** [comment]
Duplicate of #61

**Comment by Bloodevil** [comment]
close because there are duplicate issue.
