### ISSUE TITLE
Live view 

### ISSUE THREAD

**Issue by SureshbabuAkash1999** [Bloodevil/sony_camera_api#74]
Sir, could you please add a python program to stream a live view in qt5 using opencv

**Comment by mungewell** [comment]
Are you specifically looking for a OpenCV solution, or just something to run on the RaspberryPi (that you mentioned in another bug)?

The pyGame script will work on the Pi.
https://www.youtube.com/watch?v=xR3gAfu4Hfw

**Comment by SureshbabuAkash1999** [comment]
Sir, actually I am developing a gui for the same. I am able to control the
focus and take photos. But the problem is I can't send the photos to my pc.
Your help is much appreciated.

**Comment by SureshbabuAkash1999** [comment]
I am looking for an open cv solution so that I can add live view in the
window. Your help is much appreciated.

**Comment by bjmc** [comment]
@akashmon598 Hi, just to be clear: This is a free open source project supported by volunteers. This project is quite friendly and welcoming but nobody is going to do your job for you. If you want some software written, you will have to write it yourself.

If you're having a problem using this library, post a clear [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the problem that you're having, and maybe somebody will be kind enough to help -- no promises.
