### ISSUE TITLE
scan_for_cameras.py cannot find Sony Alpha(α) a6000 or a6500

### ISSUE THREAD

**Issue by eechhx** [Bloodevil/sony_camera_api#77]
Using Sony PlayMemories, I established my Sony a6000 GUID on `Windows`. With the `Send to Computer` option. I am able to connect wirelessly, but running `scan_for_cameras.py` while the camera attempts to transfer media does not return anything. 

Connecting to the access point (from `Ubuntu`) hosted via the `Send to Smartphone` option, I am able to connect. The camera shows `Sharing...` on the screen after what appears to be a "successful" connection. Running `examples/scan_for_cameras.py` with some added print statements, and you'll see that it could not find anything:

```
MESSAGE M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 5
ST: urn:schemas-sony-com:service:ScalarWebAPI:1
USER-AGENT: pysony

ADDR 239.255.255.250
PORT 1900
PACKETS dict_values([])
Available cameras: []
```
On a side note, connecting to the camera via Sony's Imaging Edge mobile app works nicely. Perhaps the SSDP address / port for mobile and computer is different? Might be related issue with https://github.com/Bloodevil/sony_camera_api/issues/60. Thanks.

**EDIT:** Just tested with Sony Alpha(α) 6500 as well, same issue.

**Comment by eechhx** [comment]
Fix was to change how you're interfacing the camera via the network. Closing.

**Comment by wildangunawan** [comment]
Sorry for bumping a two years old issue, but, can you explain more on the "how you're interfacing the camera via the network" part? I'm using A6000 as well
